language: node_js
node_js:
  - "6"
before_script:
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
  - export PATH=$HOME/.meteor:$PATH
  # Install meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam version for meteor-coverage
  - npm install -g https://github.com/serut/spacejam/tarball/windows-suppport-rc4

script:
  - npm test
  - cat .coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true # ignore coveralls error
cache:
  directories:
    - node_modules
